### ISSUE TITLE
Error logs when Geyser/Floodgate player links their account

### ISSUE THREAD

**Issue by cobaltgit** [ErdbeerbaerLP/DiscordIntegration-Fabric#10]
Sorry for not opening this issue earlier. When my friends linked their Bedrock accounts to their Discord thru Geyser, exceptions kept popping up. The linking however, worked - with a catch - the floodgateUUID field in the linked accounts file is empty, instead being in the Java UUID field

Here is the exception:
```

[17:43:01] [ForkJoinPool.commonPool-worker-2/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7aafd539[id=00000000-0000-0000-0009-01f0615ae583,name=,properties={},legacy=false]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.11.49.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.11.49.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:64) ~[authlib-3.11.49.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:61) ~[authlib-3.11.49.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[floodgate-fabric.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956) ~[floodgate-fabric.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:172) ~[authlib-3.11.49.jar:?]
        at de.erdbeerbaerlp.dcintegration.fabric.util.FabricServerInterface.getNameFromUUID(FabricServerInterface.java:147) ~[dcintegration-fabric-2.4.7-1.19.1.jar:?]
        at de.erdbeerbaerlp.dcintegration.common.util.MessageUtils.getNameFromUUID(MessageUtils.java:242) ~[de_erdbeerbaerlp_dcintegration_c.7-SNAPSHOT-cf10d96857549946.jar:?]
        at de.erdbeerbaerlp.dcintegration.common.discordCommands.CommandLink.lambda$execute$3(CommandLink.java:58) ~[de_erdbeerbaerlp_dcintegration_c.7-SNAPSHOT-cf10d96857549946.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95) ~[de_erdbeerbaerlp_dcintegration_c.7-SNAPSHOT-cf10d96857549946.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by ErdbeerbaerLP** [comment]
Should be fixed now
